# config path: '~/.config/alacritty/alacritty.toml'
[general]
    import = [
        "~/.config/alacritty/themes/themes/fallout.toml",
    ]

    live_config_reload = true

[colors]
    draw_bold_text_with_bright_colors = true

[env]
    TERM = "xterm-256color"

[font]
    size = 18.0

    [font.bold]
        ##family = "FiraCode Nerd Font"
        style  = "Bold"

    [font.bold_italic]
        #family = "FiraCode Nerd Font"
        style  = "Bold Italic"

    [font.italic]
        #family = "FiraCode Nerd Font"
        style  = "Italic"

    [font.normal]
        family = "MesloLGS Nerd Font" # "Fira Code"
        #family = "MesloLGS Nerd Font Mono"
        style  = "Regular"

    [font.offset]
        x = 0
        y = 0

[window.dimensions]
    columns = 162
    lines   = 35

[window.position]
    x = 0
    y = 0

[window.padding]
    x = 2
    y = 2

[window]
    decorations = "Buttonless"
    # for cyberdream, use https://wallhaven.cc/w/zy3l5o as bg
    opacity = 0.75
    blur = true
    startup_mode = "SimpleFullscreen"  # "Fullscreen"
